spring.application.name=nvp_server
# MySQL konekcija
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/nvp_data?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.web=DEBUG
