package com.server.nvp_server.model

import jakarta.persistence.*

enum class Permission{
    READING_USER,
    CREATING_USER,
    DELETING_USER,
    UPDATE_USER,
    CREATE_MACHINE,
    DELETE_MACHINE,
    UPDATE_MACHINE,
    STARTING_MACHINE,
    CREATING_MACHINE,
    STOPPING_MACHINE,
    RESTARTING_MACHINE,
    DESTROYING_MACHINE,
    READING_ERROR,
    READING_MACHINE,
    SCHEDULING_MACHINE
}
